"""Add ai_credit_balance

Revision ID: 0fb70a9671dc
Revises: 
Create Date: 2026-03-07 17:48:32.516612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb70a9671dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usage', sa.Column('ai_credit_balance', sa.Integer(), server_default='30000', nullable=False))
    op.drop_column('user_usage', 'daily_ai_chats_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usage', sa.Column('daily_ai_chats_count', sa.INTEGER(), server_default='0', autoincrement=False, nullable=False))
    op.drop_column('user_usage', 'ai_credit_balance')
    # ### end Alembic commands ###
