"""dodo_billing

Revision ID: c2b71a5412e6
Revises: 0373cb467ac3
Create Date: 2026-05-06 18:03:32.981313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c2b71a5412e6'
down_revision: Union[str, Sequence[str], None] = '0373cb467ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('dodo_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('dodo_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('dodo_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('billing_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscription', sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_subscription_polar_subscription_id'), table_name='subscription')
    op.create_index(op.f('ix_subscription_dodo_customer_id'), 'subscription', ['dodo_customer_id'], unique=False)
    op.create_index(op.f('ix_subscription_dodo_subscription_id'), 'subscription', ['dodo_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscription_plan'), 'subscription', ['plan'], unique=False)
    op.drop_column('subscription', 'polar_price_id')
    op.drop_column('subscription', 'polar_product_id')
    op.drop_column('subscription', 'polar_subscription_id')
    op.add_column('user', sa.Column('dodo_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_user_polar_customer_id'), table_name='user')
    op.create_index(op.f('ix_user_dodo_customer_id'), 'user', ['dodo_customer_id'], unique=True)
    op.drop_column('user', 'tier_expires_at')
    op.drop_column('user', 'tier_updated_at')
    op.drop_column('user', 'polar_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('polar_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('tier_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('tier_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_dodo_customer_id'), table_name='user')
    op.create_index(op.f('ix_user_polar_customer_id'), 'user', ['polar_customer_id'], unique=True)
    op.drop_column('user', 'dodo_customer_id')
    op.add_column('subscription', sa.Column('polar_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('polar_product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('polar_price_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscription_plan'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_dodo_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_dodo_customer_id'), table_name='subscription')
    op.create_index(op.f('ix_subscription_polar_subscription_id'), 'subscription', ['polar_subscription_id'], unique=True)
    op.drop_column('subscription', 'cancellation_reason')
    op.drop_column('subscription', 'canceled_at')
    op.drop_column('subscription', 'billing_period')
    op.drop_column('subscription', 'plan')
    op.drop_column('subscription', 'dodo_product_id')
    op.drop_column('subscription', 'dodo_customer_id')
    op.drop_column('subscription', 'dodo_subscription_id')
    # ### end Alembic commands ###
